---
# Percona Server 8.4 LTS.
mysql_version_major: "8"
mysql_version_minor: "4"

mysql_root_password: "rootPASS123#!$"

mysql_databases:
  - name: "atom"
    collation: "utf8_general_ci"
    encoding: "utf8"

mysql_users:
  - name: "atomuser"
    pass: "atomPASS9876."
    priv: "atom.*:ALL,GRANT"
    host: "%"
