---

# TODO: do we really need this task?
- name: "Create language dir symlink"
  file:
    src: "/usr/share/percona-server"
    dest: "/usr/share/mysql"
    state: "link"
  when: ansible_os_family in ['RedHat']

- name: Update configuration file
  ansible.builtin.template:
    src: "{{ mysql_config_file_template }}"
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  register: "config_file"
  notify:
    - "Restart percona"

- name: "Ensure that percona is running and enabled"
  service:
    name: "mysql"
    state: "started"
    enabled: "yes"
  register: mysql_service

# This service restart is needed when changing default mysql_datadir, mysql_native_password
# and other settings. So better restart when the config file changes
# Restart when config file has changed and it has not been restarted by the above task
- name: "Restart mysql to apply changes done in config file"
  service:
    name: "mysql"
    state: "restarted"
  when:
    - config_file.changed
    - mysql_service is defined
    - not mysql_service.changed
