---
# https://github.com/percona/repo-config-docs/blob/master/source/percona-release.rst
# https://www.percona.com/doc/percona-server/5.6/installation/apt_repo.html
# https://www.percona.com/doc/percona-server/5.7/installation/apt_repo.html
# https://www.percona.com/doc/percona-server/8.0/installation/apt_repo.html
- name: Update apt cache and install percona-release dependencies
  apt:
    name:
      - gnupg2
      - curl
      - wget
      - lsb-release
    state: present
    update_cache: yes
    cache_valid_time: 300

- block:
  # (do not put quotes on key id, for some reason it won't work)
  - name: "Obtaining percona public key"
    apt_key:
      keyserver: "keyserver.ubuntu.com"
      id: 9334A25F8507EFA5

  - name: "Adding percona repository"
    apt_repository:
      repo: "deb http://repo.percona.com/apt {{ ansible_distribution_release }} main"
      state: "present"
  when: mysql_version_major|int < 8

- block:
  - name: "Install percona-release package (Percona version >= 8)"
    apt:
      deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"

  # https://www.percona.com/doc/percona-server/LATEST/installation/apt_repo.html
  - name: "Enable Percona repository (Percona version >= 8)"
    command: "percona-release setup ps{{ mysql_version_major }}{{ mysql_version_minor }}"
  when: mysql_version_major|int >= 8

- name: "Update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 0

- block:
  - name: "Install percona packages and dependencies on Ubuntu (Percona version < 8)"
    apt:
      name:
        - "percona-server-server-{{ mysql_version_major }}.{{ mysql_version_minor }}"
        - "percona-server-client-{{ mysql_version_major }}.{{ mysql_version_minor }}"
        - "percona-toolkit"
      state: "present"

  - name: "Install percona-xtrabackup on Ubuntu (Percona version < 8)"
    apt:
      name:
        - "percona-xtrabackup"
      state: "present"
    register: percona_xtrabackup_install
    ignore_errors: yes

  - name: "Install percona-xtrabackup-24 on Ubuntu (Percona version < 8)"
    apt:
      name:
        - "percona-xtrabackup-24"
      state: "present"
    when:
    - percona_xtrabackup_install.failed
  when: mysql_version_major|int < 8

- name: "Install | configure debconf for version 8.0 (Use Legacy Authentication Method)"
  debconf:
    name: 'percona-server-server'
    question: 'percona-server-server/default-auth-override'
    value: 'Use Legacy Authentication Method (Retain MySQL 5.x Compatibility)'
    vtype: select
  changed_when: false
  when:
    - mysql_version_major|int >= 8
    - mysql_default_authentication_plugin is defined
    - mysql_default_authentication_plugin == "mysql_native_password"

- name: "Install percona packages and dependencies on Ubuntu (Percona version >= 8)"
  apt:
    name:
      - "percona-server-server={{ mysql_version_major }}.{{ mysql_version_minor }}*"
      - "percona-server-client={{ mysql_version_major }}.{{ mysql_version_minor }}*"
      - "percona-toolkit"
      - "percona-xtrabackup-80"
    state: "present"
  when: mysql_version_major|int >= 8

- name: "Install package dependencies for ansible MySQL modules"
  apt:
    name: "python{{ ansible_python_version is version('3', '>=') | ternary('3', '') }}-mysqldb"

- name: "Adjust permissions of datadir"
  file:
    path: "{{ mysql_datadir }}"
    owner: "mysql"
    group: "mysql"
    mode: 0700
    state: "directory"
