---
# (do not put quotes on key id, for some reason it won't work)
- name: "Obtaining percona public key"
  apt_key: 
    keyserver: "keyserver.ubuntu.com"
    id: 8507EFA5
  become: yes

- name: "Adding percona repository"
  apt_repository: "repo='deb http://repo.percona.com/apt {{ ansible_distribution_release }} main' state=present"
  become: yes
  when: "ansible_distribution_release != 'xenial'"

- name: "Adding percona repository (use wily packages as xenial package N/A yet)"
  apt_repository: "repo='deb http://repo.percona.com/apt wily main' state=present"
  become: yes
  when: "ansible_distribution_release == 'xenial'"

- name: "Update apt cache"
  apt: "update_cache=yes cache_valid_time=300"
  become: yes

- name: "Install percona database server"
  action: "apt pkg={{ item }} state=latest"
  with_items:
    - "percona-server-server-5.5"
    - "percona-server-client-5.5"
    - "percona-toolkit"
    - "percona-xtrabackup"
    - "python-mysqldb"
  become: yes

- name: "Adjust permissions of datadir"
  file: "path={{ mysql_datadir }} owner=mysql group=mysql mode=0700 state=directory"
  become: yes

- name: "Ensure that percona is running"
  service: "name=mysql state=started"
  become: yes

- name: "Ensure that percona is enabled"
  service: "name=mysql enabled=yes"
  become: yes
