---
# (do not put quotes on key id, for some reason it won't work)
- name: "Obtaining percona public key"
  apt_key: 
    keyserver: "keyserver.ubuntu.com"
    id: 9334A25F8507EFA5

- name: "Adding percona repository"
  apt_repository:
    repo: "deb http://repo.percona.com/apt {{ ansible_distribution_release }} main"
    state: "present"

- name: "Update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 300

- name: "Get the major version of python used to run ansible"
  command: "{{ ansible_python_interpreter | default('/usr/bin/python') }} -c 'import sys; print(sys.version_info.major)'"
  register: ansible_python_major
  changed_when: false

- debug:
    msg: "ansible_python_interpreter major version: {{ ansible_python_major.stdout }}"

- name: "Install package dependencies for ansible MySQL modules (python 2)"
  apt:
    name: "python-mysqldb"
  when:
    - ansible_python_major.stdout == "2"

- name: "Install package dependencies for ansible MySQL modules (python 3)"
  apt:
    name: "python3-mysqldb"
  when:
    - ansible_python_major.stdout == "3"

- name: "Install percona packages and dependencies on Ubuntu"
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
     - "percona-server-server-{{ mysql_version_major }}.{{ mysql_version_minor }}"
     - "percona-server-client-{{ mysql_version_major }}.{{ mysql_version_minor }}"
     - "percona-toolkit"
     - "percona-xtrabackup"

- name: "Adjust permissions of datadir"
  file:
    path: "{{ mysql_datadir }}"
    owner: "mysql"
    group: "mysql"
    mode: 0700
    state: "directory"

- name: "Ensure that percona is running and enabled"
  service:
    name: "mysql"
    state: "started"
    enabled: "yes"
