---

- name: Verify
  hosts: all
  tasks:
    - name: Make sure we can connect to MySQL via Unix socket.
      command: "mysql -u root -e 'show databases;'"
      become: true
      changed_when: false

    - name: Make sure we can connect to MySQL via TCP.
      command: "mysql -u root -h 127.0.0.1 -e 'show databases;'"
      become: true
      changed_when: false

    - name: Show server status
      block:
        - command: "mysql -u root -NBe 'status'"
          become: true
          changed_when: false
          register: mysql_status

        - debug:
            var: mysql_status.stdout
